### ISSUE TITLE
'dd' - Blocks in index.html

### ISSUE THREAD

**Issue by mic-men** [dini-ag-kim/hs-oer-lom-profil#13]
Mir ist aufgefallen, dass es ein ReSpec - Problem in manchen 'dd' - Blöcken zu geben scheint.
Die Ende-Tags erscheinen dort im fertig gerenderten HTML.
Bsp. (kein Anspruch auf Vollständigkeit): 'metadata' Attribute, 'aggregationlevel' value, 'lifecycle' contributer roles.
Scheint in allen Versionen, inkl. master-Branch und auch /latest so zu sein.
Getestet mit Firefox und Chromium.

**Comment by acka47** [comment]
Ich bin mir ziemlich sicher, dass das bis vor kurzem noch gut aussah. @sebastian-meyer, kann es sein, dass diese Probleme mit 46bac9494cd162fe6e190a0f6502acbe7aa6c42f reingekommen sind?

**Comment by sebastian-meyer** [comment]
Ja, der Markdown-Prozessor in ReSpec wurde kürzlich verbessert und erkennt jetzt auch Markdown, wenn es in HTML eingebettet ist.
Dadurch wird jetzt der Text innerhalb der `<dd></dd>` korrekt als Markdown erkannt und entsprechend formatiert. Da der Textblock jedoch eingerückt ist, wird das vom Markdown-Prozessor (korrekt) als Code-Auszeichnung interpretiert.

Um das Problem zu beheben, muss bei Markdown-Absätzen darauf geachtet werden, dass sie nicht eingerückt sind (bzw. nur dann, wenn sie als Code-Block interpretiert werden sollen). Markdown-Absätze sind alle Absätze, die nicht mit einem HTML-Element beginnen. (Deshalb betrifft es nicht alle `<dd></dd>`-Elemente, da bei den meisten das Markdown in derselben Zeile wie das öffnende HTML-Tag steht.)

**Comment by sebastian-meyer** [comment]
Die Bedeutung der Textformatierung in Markdown ist hier gut dokumentiert: https://github.github.com/gfm/

**Comment by sebastian-meyer** [comment]
Ich repariere die Specs und stelle einen Pull-Request.
