### ISSUE TITLE
Nutze W3ID-Links wo möglich

### ISSUE THREAD

**Issue by acka47** [dini-ag-kim/hs-oer-lom-profil#17]
Momentan werden alle relativen Links mit dem GitHub Pades Namespace ergänzt
Beispiele:

- `[XML Schema Description](schemas/hs-oer-lom.xsd)` -> https://dini-ag-kim.github.io/hs-oer-lom-profil/draft/schemas/hs-oer-lom.xsd
- `[Link zum Beispiel](examples/general-example.xml)` - > https://dini-ag-kim.github.io/hs-oer-lom-profil/draft/examples/general-example.xml

Gibt es eine Möglichkeit, dass stattdessen der W3ID-Namespace genutzt wird (z.B https://w3id.org/kim/hs-oer-lom-profil/draft/schemas/hs-oer-lom.xsd)?

**Comment by sebastian-meyer** [comment]
Da es sich um relative Links handelt (`schemas/hs-oer-lom.xsd`), wird immer die aktuelle Domain vorangestellt - und das ist nunmal die GitHub Pages-Domain, weil die W3ID-URLs ja nur dorthin weiterleiten.
Man könnte einfach absolute Links verwenden, aber dann müsste man die Links jedesmal anpassen, wenn aus einem Draft eine publizierte Fassung wird.

**Comment by acka47** [comment]
Hmm, schade. Das ist ja schon ein bisschen blöd, wenn Menschen Links auf solche Elemente verschicken und sich dann die Publikatios-URL ändert. Das gleich gilt allerdings auch für die Anchor-Links. Das könnte man dann nur mit einem Reverse Proxy lösen, oder wie?

Ich hatte gehofft, es gäbe in Respec zumindest für die relativen Links eine Funktion, umden Namespace anzugeben, so dass bei der Generierung des HTML absolute Links aus den relativen gebaut werden. Dann müsste man nur eine Angabe anpassen, wenn der Draft publiziert wird...

**Comment by sebastian-meyer** [comment]
Das liegt einfach an der Art, wie W3ID funktioniert. Das sind alles harte Redirects und keine Aliase.

Ich könnte mal versuchen, ob die Angabe einer [Base-URL](https://developer.mozilla.org/de/docs/Web/HTML/Element/base) einen Unterschied macht.

**Comment by acka47** [comment]
> Ich könnte mal versuchen, ob die Angabe einer Base-URL einen Unterschied macht.

+1

**Comment by sebastian-meyer** [comment]
Das hat tatsächlich funktioniert. 😄

**Comment by sebastian-meyer** [comment]
Leider zu früh gefreut. Die w3id.org-URLs führen bei relativen Links leider zu einer endlosen Redirect-Schleife...
Ich nehme sie daher wieder raus.
