### ISSUE TITLE
Schema Namespace

### ISSUE THREAD

**Issue by acka47** [dini-ag-kim/hs-oer-lom-profil#18]
Ich wundere mich gerade, dass der Namespace für das XML-Schema `https://www.oerbw.de/hsoerlom` ist. Da gibt es sicher einen Grund für? Wäre es nicht sinnvoll, da auch etwas im `https://w3id.org/kim/hs-oer-lom-profil`-Namespace zu nehmen?

**Comment by mic-men** [comment]
Das mag theoretisch richtig sein. Letztendlich ist es nur ein Bezeichner und ich kann das jetzt an anderer publizierter Stelle nicht mehr ändern. Insofern bitte ich darum, es so zu belassen.

**Comment by acka47** [comment]
Ok.
