### ISSUE TITLE
Inkonsistente VCard-Angaben

### ISSUE THREAD

**Issue by acka47** [dini-ag-kim/hs-oer-lom-profil#28]
@TobiasNx hat mich auf das Problem aufmerksam gemacht. (Siehe https://gitlab.com/oersi/oersi-etl/-/issues/62#note_579227388 wo er das entsprechende Problem in der EduSharing-API beschreibt.)

In den Beispielen wird die VCard einer Organisation gerade wie folgt dargestellt:

https://github.com/dini-ag-kim/hs-oer-lom-profil/blob/04bf6ae77cd134fcb4f0272e7f79fa458f376d83/20210506/examples/full-example-a.xml#L102-L108

Das Beispiel gibt als VCard-Version "3.0", die aber ausschließlich zur Repräsentation von Personen gedacht zu sein scheint, siehe [RFC 2426](https://datatracker.ietf.org/doc/html/rfc2426):

> This memo defines the profile of the MIME Content-Type [MIME-DIR] for
   directory information for a white-pages person object, based on a
   vCard electronic business card.

Prinzipiell sollte der `ORG`-Schlüssel in einer VCard dazu benutzt werden, die Affiliierung einer Person mit einer Organisation anzugeben, siehe https://datatracker.ietf.org/doc/html/rfc2426#section-3.5.5. 

Eine Unterscheidung zwischen VCards für Individuen, Gruppen und Organisationen wurde erst mit Version 4.0 und dem `KIND`-Schlüssel eingeführt. Das ist wiederum [RFC 6350](https://datatracker.ietf.org/doc/html/rfc6350), der auch in der Spezifikation referenziert wird, siehe https://dini-ag-kim.github.io/hs-oer-lom-profil/latest/#bib-rfc6350. Gemäß der 4.0 Spec ([Abschnitt 6.1.4](https://datatracker.ietf.org/doc/html/rfc6350#section-6.1.4)) würde die VCard einer Organisation dann so aussehen:

```xml
<vcard>
    BEGIN:VCARD
    VERSION:3.0
    KIND:org
    FN:Universität Tübingen
    URL:https://www.wikidata.org/entity/Q153978
    END:VCARD
</vcard>
```

Wir sollten hier a) konsistent auf dieselbe VCard-Version in der Spec und den Beispielen verweisen und b) Organisationen-VCards richtig darstellen. Das heißt:

1. In den Beispielen Version 4.0 angeben
2. Organisationen VCards in den Beispielen wie oben gezeigt (mit `KIND:org` und `FN:{Name}`) angeben.

**Comment by TobiasNx** [comment]
Vielleicht auch in der Specs explizit darauf hinweisen, dass Version 3.0 Organisationen nicht richtig abbilden kann und dafür Version 4.0 benötigt wird.

**Comment by mic-men** [comment]
Danke für den Hinweis. Wir werden in der Spezifikation auf die VCard Version 4.0 umstellen und die Eigenschaft KIND nutzen.

**Comment by acka47** [comment]
Wir müssen noch eine neue Version publizieren, weshalb ich das Ticket mal wieder öffne. @mic-men, wir sollten vorher auch noch Kommentare in einer Reviewphase ermöglichen. Kannst du dazu eine Mail an die Liste schicken analog zu https://lists.dnb.de/pipermail/dini-ag-kim-oer/2021-March/000165.html?

**Comment by acka47** [comment]
Ich habe mal https://github.com/dini-ag-kim/stoeberspecs/issues/6 aufgemacht, damit die Reviewphase auch bei den Prozessen dokumentiert ist.

**Comment by mic-men** [comment]
Korrektur ist in Release vom 9.9.2021 integriert.
