### ISSUE TITLE
LearningResourceType-Werteliste als SKOS-Vokabular veröffentlichen

### ISSUE THREAD

**Issue by acka47** [dini-ag-kim/hs-oer-lom-profil#3]
Momentan sind die Werte als Strings definiert, siehe https://dini-ag-kim.github.io/hs-oer-lom-profil/draft/#dfn-learningresourcetype. Es handelt sich derzeit um 24 Werte:

```
application - Anwendung, Software
assessment - Lernkontrolle, (Selbst-)Test
audio - Tonaufnahme
case_study - Fallstudie
course - Lernkurs
data - (Roh-, Beispiel-) Daten
diagram - Diagramm, Grafik
drill_and_practice - Übung
educational_game - Lernspiel
experiment - Experiment
image - Abbildung, Foto, Bild
index - Glossar, Nachschlagewerk, Wiki, Lexikon
lesson_plan - Unterrichtsplanung, Unterrichtsgestaltung
map - Karte
portal - (Web-, Wissens-) Portal
questionnaire - Fragebogen, Rechercheauftrag
script - Skript
simulation - Simulation
slide - Präsentation, Folien
text - Artikel, Aufstatz, Text, Abhandlung
video - Video
web_page - Webseite
worksheet - Arbeitsblatt, Arbeitsmaterial
other - sonstiges
```

Ein SKOS-Vokabular würde einige Vorteile mit sich bringen:

- URIs für die einzelnen Werte
- einheitliche Namensvorschläge mit `skos:prefLabel`
- Trennung von Name und Definition (z.b. Aufzählung der verschiedenen Beispiele eine Typs in `skos:scopeNote`)
- Multilingualität möglich
- Lookup kann mittels SkoHub umgesetzt werden
- ...

Die Spezifikation müsste dann natürlich entsprechend angepasst werden.

**Comment by acka47** [comment]
Eine erste Version ist hier: https://skohub.io/dini-ag-kim/hccm/heads/master/w3id.org/dini-ag-kim/hccm/scheme.html ([GitHub repo](https://github.com/dini-ag-kim/hccm)).

Ich habe den Namen etwas angepasst ("Hochschulcampus Custom Content Model"). Bevor ich die W3ID-URI und den Redirect anlege, sollten wir uns sicher sein, ob der Name und das Akronym tatsächlich verwendet werden sollten. @mic-men, was meinst du?

**Comment by mic-men** [comment]
Prima, danke für die Umsetzung in SKOS!

Warum ist Dir so wichtig, die Begriffe "Custom" und "Content" umzudrehen?
Ich habe mich an einen Namen in edu-sharing angelehnt (Campus Content Custom Model), wobei ich aber
nicht behaupte, dass über die Bezeichnung tiefgründig nachgedacht wurde (ich weiss es nicht).
Wenn ich nochmal darüber nachdenke, halte ich es eher für überlegenswert, "Custom" ganz wegzulassen.
Was meinst Du?
Jedenfalls alle Stellen zu ändern, um die beiden Begriffe umzudrehen, halte ich nicht für notwendig,
dann würde ich es lieber so lassen.

Das Akronym ist gut und kann ja in jedem Fall so bleiben, ob mit vertauschten Worten oder ganz ohne
"Custom".


Am 06.02.20 um 10:56 schrieb Adrian:

**Comment by mic-men** [comment]
Mir wird klar, dass es viel sinnvoller ist, im <source> Tag anstelle der Bezeichner die URLs zu verwenden, also
"https://w3id.org/dini-ag-kim/hccm/scheme" statt "Hochschulcampus Content (Custom) Model"
und
"https://w3id.org/class/hochschulfaechersystematik/scheme#" statt "Hochschulfaecher".
Damit sind die Bezeichner nur noch in Erläuterungen/Beschreibungen notwendig.
Ich tendiere übrigens immer stärker zu "Hochschulcampus Content Model".
@acka47 , wie siehst Du das?

**Comment by acka47** [comment]
Ich finde "Hochschulcampus Content Model" besser aber auch nicht besonders sprechend. "Learning Resource Type Vocabulary", "Hochschulcampus Resource Types" o.ä.  wäre aussagekräftiger.

**Comment by acka47** [comment]
Wir haben uns jetzt offline auf "Hochschulcampus Lernressourcen" geeinigt , siehe https://github.com/dini-ag-kim/hcrt/commit/445d33c2fe8118f2842abcb42f33e50b0da64df1

**Comment by mic-men** [comment]
Korrektur: Wir haben uns auf "Hochschulcampus **Ressourcentypen**" geeinigt! Die Änderungen im angeg. Link sind auch entsprechend korrekt.

**Comment by acka47** [comment]
Oups, ja so ist es.

**Comment by acka47** [comment]
Erledigt, der Perma-URI ist https://w3id.org/kim/hcrt/scheme.
