### ISSUE TITLE
Ergänze Angabe zum maximalen Vorkommen bei Mehrfachelementen

### ISSUE THREAD

**Issue by acka47** [dini-ag-kim/hs-oer-lom-profil#8]
Siehe 
- https://hyp.is/hHpBskaAEeqokHPDuNaEzA/dini-ag-kim.github.io/hs-oer-lom-profil/draft/
- https://hyp.is/tgun1EaAEeq4uG_JBG6S1g/dini-ag-kim.github.io/hs-oer-lom-profil/draft/
- https://hyp.is/ophPbEaBEeq6-T_i_fZcnA/dini-ag-kim.github.io/hs-oer-lom-profil/draft/
- https://hyp.is/2bzZ0EaCEeq4MUeUBxf5mQ/dini-ag-kim.github.io/hs-oer-lom-profil/draft/

**Comment by mic-men** [comment]
Die Angaben zum max. Vorkommen kann ich noch überarbeiten. Die englische Formulierung ist da immer so:
> "The <description> element occurs 0 or more times within the <general> element. The smallest permitted maximum is 10 instances within the <general> element."

Wie sagt man das vernünftig in deutsch, so dass es verständlich ist: "smallest permitted maximum"?
Auch im englischen muss es nochmal erläutert werden (können wir auch machen, intuitiv klar wäre besser):

> "The reader's attention is called to LOM's "smallest permitted maximum" concept. Implementations are not guaranteed to handle more than a smallest permitted maximum declared for a given element or string length."

Ich bitte um Vorschläge einer guten deutschen Übersetzung. @sebastian-meyer , Du hast Dich doch schon intensiv mit der Übersetzung in Spezifikationen beschäftigt?

**Comment by mic-men** [comment]
Dank an Frank für die hilfreichen Annotationen!
Zuerst, was ich nicht ändern möchte:
- Der metametadata [Provider](https://hyp.is/rMMpzkaDEeqfkF8xZb39DQ/dini-ag-kim.github.io/hs-oer-lom-profil/draft/) soll so bleiben, ohne dass wir ein eigenes Vokabular definieren. Das mag nicht 100% korrekt sein, aber sonst ist es wie mt Kanonen auf Spatzen schießen.
- [Relationen](https://hyp.is/e00ztkaJEeqjVftmCRkn5w/dini-ag-kim.github.io/hs-oer-lom-profil/draft/): Das ist sicher richtig und auch wichtig, aber keiner von uns hat bisher ein vernünftiges Szenario im Einsatz. Bei Bedarf wird das ergänzt. Wenn wir es jetzt machen, haben wir ein schönes theoretisches Gebilde, das dann im Einsatz nicht passt.
- [Klassifikation - Kompetenzrahmen](https://hyp.is/hQxOgEZ8Eeq9AlNFnNCjxw/dini-ag-kim.github.io/hs-oer-lom-profil/draft/). Keiner der Partner hatte da bisher Bedarf. Sollte der konkret auftreten, können wir das zu geg. Zeit ergänzen. 

Jetzt aber zu den anderen Punkten:
- Dann referenzieren wir offiziell zur [Version](https://hyp.is/T55M-EgqEeqm7pd8KydATQ/dini-ag-kim.github.io/hs-oer-lom-profil/draft/) 1.2.4, die Fußnote kann dann aber nur auf die allg. Seite mit allen Versionen verweisen. Im Text bleibt es bei "LOMv1.2" - ist das so ok?
- Den Vorschlag eines [Vokabulars für die catalogentry](https://hyp.is/H0j9IkghEeqmghuMt5qmHw/dini-ag-kim.github.io/hs-oer-lom-profil/draft/) - Sourcen finde ich gut und werde ich integrieren.
- Der [Taxonpfad](https://hyp.is/4tBjykgmEeqxg-MI_lGzAg/dini-ag-kim.github.io/hs-oer-lom-profil/draft/) kann in eine Liste statt eine Hierarchie - wenn die Profis sagen, dass es so besser ist, machen wir das - werde ich umarbeiten.
- Die [Mehrfach-Elemente](https://github.com/dini-ag-kim/hs-oer-lom-profil/issues/8#issue-560407226): Da können wir uns gern zum größten Teil an die Vorgaben aus LOM halten. Folgende Elemente werde ich dann mit einem "smallest permitted maximum" versehen, wenn die deutsche Formulierung klar ist, s. vorigen Kommentar:
  + title : 1 (das ist Absicht!)
  + catalogentry: 10 (auch hier überlege ich noch '1' zu sagen - Meinungen?)
  + format: 40
  + taxonpath: 15
Eine Annotation mit Wert 30 konnte ich nicht zuordnen, da das hypotes.is nicht richtig funktioniert.

**Comment by sebastian-meyer** [comment]
Ich kenne es aus anderen Standards so, dass zwischen Spezifikation und Implementierungsdetails unterschieden wird. Konkret würde das heißen, dass innerhalb des normativen Teils der Spezifikation - also bei der Definition des jeweiligen Elements - die tatsächlich erlaubte Anzahl genannt wird (also "0 oder mehr" ohne Maximum). Außerdem würde man dort auf einen eigenen Abschnitt "Implementierung" verweisen, in dem dann definiert wird, dass implementierende Systeme für bestimmte Felder mindestens ein bestimmtes Limit unterstützen müssen (also "mindestens 10 Iterationen").

Die Unterscheidung finde ich wichtig, weil sie ja unterschiedliche Zielgruppen betrifft: Als Metadaten-Erzeuger ist für mich nur wichtig zu wissen, dass ich prinzipiell beliebig viele `<format>` angeben kann. Als Implementierer eines technischen Systems, das diese Metadaten verarbeiten soll, muss ich außerdem wissen, dass das System mindestens 10 verschiedene `<format>` interpretieren können muss.

(Wobei ich eine solche Angabe generell etwas antiquiert finde. Heutzutage sollte ein technisches System in der Lage sein, ein beliebig oft vorkommendes Metadatenfeld auch beliebig oft interpretieren zu können. In der Praxis ist die Anzahl ja trotzdem immer endlich.)

**Comment by mic-men** [comment]
Im ersten Moment fand ich das Argument der Antiquiertheit einleuchtend, es sollte für ein
technisches System tatsächlich kein Problem sein, diese Metadaten zu interpretieren.
Nach etwas Nachdenken ist mir aber aufgegangen, dass es noch eine weitere Seite gibt. Was*muss* dem
Nutzer präsentiert werden? Und da ist das Design häufig so, dass aus verschiedenen Gründen eben
nicht beliebig viele Werte für manche Metadaten angezeigt werden. Z.B. ist ist häufig nur 1 Titel
vorgesehen. Ein System, das nur 1 Titel anzeigt, wäre doch dann nicht mehr konform zum Profile, oder?
Insofern ist für mich die Separation der Implementierung auch nicht einleuchtend. Als Anbieter
sollte ich doch schon berücksichtigen, welche meiner Angaben auf jeden Fall interpretiert werden,
oder? Und was gehörte in einen solchen Abschnitt "Implementierung" noch hinein?
Andererseits, wenn in der Praxis sowieso jedem überlassen bleibt, was er überhaupt nutzt - was mir
realistisch erscheint -, dann ist eine solche Angabe wirklich überflüssig, aber nicht aus dem
Argument heraus, dass es für technische Systeme prinzipiell kein Problem wäre, alle Daten zu
interpretieren. Aber dann verstehe ich auch nicht richtig das Konzept hinter "smallest permitted
maximum".

Ich bitte um Kommentare und Meinungen. Wenn keine kommen, werde ich die meisten Beschränkungen
fallen lassen und einfach nichts in dieser Hinsicht hineinschreiben.

**Comment by sebastian-meyer** [comment]
Ich finde es nicht richtig, in einem Anwendungsprofil für einen *Daten*standard Anforderungen an deren *Präsentation* oder *Weiterverarbeitung* zu stellen. Daten sollten immer systemagnostisch sein, d. h. sie sollten die zu transportierenden Informationen bestmöglich strukturieren und höchstens auf bestimmte Anwendungszwecke (aber nicht konkrete Lösungen) zugeschnitten sein.

Deshalb würde ich Implementierungsempfehlungen idealerweise nicht in die Spezifikation für das Datenformat stecken - und wenn doch, dann zumindest deutlich vom normativen Standard getrennt in Form eines rein informativen Abschnitts. (In ReSpec kann man informative Absätze übrigens mit der HTML-Klasse `informative` kennzeichnen.)

Langer Rede kurzer Sinn: Ich stimme dir zu und würde die Beschränkungen auch einfach weglassen! ;)
